# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/projeto

    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            set -xu
            mkdir -p /tmp/artifacts
            echo "conteudo" > /tmp/artifacts/arquivo.txt;

      - store_artifacts:
          path: /tmp/artifacts
          destination: build

      - run:    
          name: PWD
          command: |
            pwd

      - persist_to_workspace:
          root: /tmp/artifacts
          paths:
            - arquivo.txt
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       scp .dist/artifacts/artifact-2 $SSH_USER@$SSH_HOST:~/teste/

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/projeto

    steps:
      - run:
          name: PWD
          command: |
            pwd            
      
      - run:
          name: LS1
          command: |
            ls -lia

      - attach_workspace:
          at: /tmp

      - run:
          name: LS2
          command: |
            ls -lia 
      - run:
          name: LS3
          command: |
            ls -lia /
      - run:
          name: LS4
          command: |
            ls -lia /tmp
      # - run:
      #     name: LS
      #     command: |
      #       ls -lia ../projeto/pastaX     

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master            
