# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
    working_directory: ~/projeto

    steps:
      - checkout
      - run: 
          name: ls -lia
          command: |
            ls -lia
      
      

      - persist_to_workspace:
          root: /home/circleci/projeto/
          paths:
            - app/

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
    working_directory: ~/projeto

    steps:
      - run:
          name: ls -lia /
          command: |
            ls -lia /

      - run:
          name: ls -lia /etc/ssh
          command: |
            ls -lia /etc/ssh

      - run:
          name: ls -lia /tmp
          command: |
            ls -lia /tmp
      
      - attach_workspace:
          at: /tmp

      - run:
          name: LS4
          command: |
            ls -lia /tmp
      - run:
          name: LS4
          command: |
            ls -lia /tmp/app

      - run:
          name: Deploy Over SSH
          command: |
            ssh-keyscan $SSH_HOST >> /etc/.ssh/config 

      - run:
          name: Deploy Over SSH
          command: |
            scp temp/dist/ $SSH_USER@$SSH_HOST:~/dist


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master            
