# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
    working_directory: ~/projeto

    steps:
      # - checkout
      - run: 
          name: teste
          command: |
            ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

      - run: 
          name: cat
          command: |
            cat ~/.ssh/id_rsa.pub

      # - run:
      #     name: pwms.com.br
      #     command: ssh-keyscan -H pwms.com.br >> ~/.ssh/known_hosts            


      # - persist_to_workspace:
      #     root: /home/circleci/projeto/
      #     paths:
      #       - app/

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
    working_directory: ~/projeto

    steps:

      - run: 
          name: ssh-keygen 
          command: |
            ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa

      - run: 
          name: cat ~/.ssh/id_rsa.pub
          command: |
            cat ~/.ssh/id_rsa.pub

      - run:
          name: ssh-keyscan
          command: ssh-keyscan -H pwms.com.br >> ~/.ssh/known_hosts    


      # - run:
      #     name: ls -lia /etc/ssh/ssh_config
      #     command: |
      #       ls -lia /etc/ssh/ssh_config

      # - run:
      #     name: ls -lia /tmp
      #     command: |
      #       ls -lia /tmp
      
      # - attach_workspace:
      #     at: /tmp

      # - run:
      #     name: LS4
      #     command: |
      #       ls -lia /tmp
      # - run:
      #     name: LS4
      #     command: |
      #       ls -lia /tmp/app

      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       sudo ssh-keyscan pwms.com.br >> /etc/ssh/ssh_config

      - run:
          name: mkdir teste
          command: |
            touch teste.txt

      - run:
          name: Deploy Over SSH
          command: |
            scp teste.txt waisoc@pwms.com.br:/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master            
