# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/projeto

    steps:
      - checkout

      - run:
          name: PWD 1
          command: pwd

      - run:
          name: LS 1
          command: ls -lia

      # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "app/package.json" }}
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: cd app && npm install
      - run:
          name: install angular CLI
          command: sudo npm install -g @angular/cli

      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "app/package.json" }}
          paths:
              - node_modules 
      - run:
          name: PWD 2
          command: pwd

      - run:
          name: LS 2
          command: ls -lia

      - run:
          name: build angular
          command: cd app && ng build

      - run:
          name: LS 3
          command: ls -lia

      - run:
          name: PWD 3
          command: pwd
              
      - store_artifacts:
          path: app/dist
          destination: dist          

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: PWD 4
          command: |
            pwd            
      - run:
          name: LS 4
          command: |
            ls -lia /home
      - run:
          name: LS 4
          command: |
            ls -lia /home/circleci   
      - run:
          name: LS 4
          command: |
            ls -lia /home/circleci/project  
      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       scp dist/primeiro-projeto/* $SSH_USER@$SSH_HOST:~/dist

      # - run:
      #     name: Deploy Over SSH
      #     command: |
      #       scp /home/circleci/repo/README.md $SSH_USER@$SSH_HOST:~/

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master            
