# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/my-project

    steps:
      - run:
          name: Creating Dummy Artifacts
          command: |
            set -xu
            mkdir -p /tmp/artifacts
            echo "conteudo" > /tmp/artifacts/arquivo.txt;

      - store_artifacts:
          path: /tmp/artifacts
          destination: build

      - run:    
          name: PWD
          command: |
            pwd

      - persist_to_workspace:
          root: /tmp/artifacts
          
  deploy-stage:
    docker:
      - image: circleci/node:8.9
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Staging
          command: ls -lia          
          
  deploy-prod:
    docker:
      - image: ubuntu:14.04
    working_directory: /tmp/my-project  
    steps:
      - run:
          name: Deploy if tests pass and branch is Master
          command: ls  -lia


workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: staging
      - deploy-prod:
          requires:
            - build
          filters:
            branches:
              only: master              
